FILTERS: Adding MeshIO reader and writers.
BlueQuartzSoftware/complex pull request #1009
Opened 2024-06-29 09:58 UTC by joeykleingers

Adds the following filters:

+ ReadMeshFile
+ WriteAbaqusFile
+ WriteAnsysFile
+ WriteGmshFile
+ WriteMedFile
+ WriteTetGenFile
+ WriteVtuFile

Also exposes a new method called numpy_dtype_to_datatype to Python that converts numpy dtypes to NX DataTypes.

2024-07-01 14:59 UTC, JDuffeyBQ requested changes

2024-07-01 14:59 UTC, JDuffeyBQ commented on src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
> +      "numpy_dtype_to_datatype",
```suggestion
      "convert_np_dtype_to_datatype",
```
I think adding "convert" helps make it clear that this is a function. And shortening "numpy" to "np" helps to keep it from getting too long.

2024-07-01 15:23 UTC, imikejackson approved these changes

2024-07-03 12:25 UTC, StopkaKris commented
Very cool! I will definitely be testing this in the next release.

2024-07-03 15:32 UTC, JDuffeyBQ approved these changes

2024-07-03 19:19 UTC, merged