BUG/API: Histogram Sync
BlueQuartzSoftware/complex pull request #1073
Opened 2024-09-17 18:16 UTC by nyoungbq

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `simplnx/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `simplnx/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

2024-09-24 20:21 UTC, imikejackson approved these changes

2024-09-25 15:07 UTC, JDuffeyBQ requested changes

2024-09-25 15:07 UTC, JDuffeyBQ commented on src/simplnx/DataStructure/IDataStore.hpp
> +    return getNumberOfTuples() * getNumberOfComponents();
```suggestion
    return getSize();
```
We can implement `size()` using `getSize()`.

2024-09-25 15:07 UTC, JDuffeyBQ commented on src/simplnx/Utilities/HistogramUtilities.hpp
> +    if((bin >= 0) && (bin < numBins))
`bool` histograms should probably be a special case.

2024-09-25 21:01 UTC, imikejackson approved these changes

2024-09-26 00:52 UTC, JDuffeyBQ approved these changes

2024-09-26 11:05 UTC, merged