Added InitializeData filter
BlueQuartzSoftware/complex pull request #121
Opened 2022-02-17 20:17 UTC by JDuffeyBQ

2022-02-18 16:38 UTC, mmarineBlueQuartz submitted a review, later dismissed

2022-02-18 18:10 UTC, JDuffeyBQ commented
(min, max) for each x/y/z or (x, y, z) for each min/max? The code example is different from the text.

2022-02-18 23:24 UTC, imikejackson commented
I tried xyz Min and xyz max and it looked ok from a visual point of view. I never know which way to go on these. 3 sets of 2 or 2 sets of 3. either way works as we get to label everything in the GUI.

2022-02-23 21:13 UTC, imikejackson requested changes
Change the input parameters for the min max and this should be good to go.

2022-03-04 17:29 UTC, imikejackson approved these changes

2022-03-04 18:33 UTC, merged