Feature/ExtractInternalSurfacesFromTriangleGeometry
BlueQuartzSoftware/complex pull request #124
Opened 2022-02-18 14:49 UTC by mmarineBlueQuartz

* Added ExtractInternalSurvacesFromTriangleGeom filter
* Added unit test
* Added CreateTriangleGeomAction
* Renamed DataObject::getParentDataPaths to getDataPaths due to misleading name. DataObject::getParentDataPaths did not return DataPaths to known parents. It returned the DataPaths to the object calling it.

2022-02-18 18:02 UTC, JDuffeyBQ reviewed
The `DataObject::getParentDataPaths()` changes should probably be in a separate PR. And I thought there was already a change about that function?

2022-02-23 14:44 UTC, imikejackson commented
@mmarineBlueQuartz  What is the function `getDataPaths()` *supposed* to return? Because it returns the DataPaths of all the parents of the object. If it is *supposed* to return the children DataPaths then there is a logic error in the function.

2022-03-08 17:51 UTC, JDuffeyBQ requested changes
This just needs the `getDataPaths()` changes extracted to a separate PR with whatever name we ended up deciding on.

2022-03-08 17:51 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.cpp
> +  typedef std::unordered_map<Vertex, int64, ArrayHasher> VertexMap;
```suggestion
  using Triangle = std::array<int64, 3>;
  using VertexMap = std::unordered_map<Vertex, int64, ArrayHasher>;
```

2022-03-15 15:18 UTC, imikejackson approved these changes

2022-03-15 15:20 UTC, merged