FILTER: Align Geometries
BlueQuartzSoftware/complex pull request #139
Opened 2022-02-25 14:17 UTC by mmarineBlueQuartz

* Added AlignGeometries filter
* Added unit test

2022-03-01 19:16 UTC, JDuffeyBQ requested changes

2022-03-01 19:16 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +  if(auto* image = dynamic_cast<const complex::ImageGeom*>(geometry))
These `if` blocks could be replaced with a `switch` on `AbstractGeometry::Type`. And the same for the other functions.

2022-03-01 19:16 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +complex::FloatVec3 extractOrigin(const complex::AbstractGeometry* geometry)
```suggestion
complex::FloatVec3 extractOrigin(const complex::AbstractGeometry& geometry)
```

2022-03-01 19:16 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +void translateGeometry(complex::AbstractGeometry* geometry, const complex::FloatVec3& translation)
```suggestion
void translateGeometry(complex::AbstractGeometry& geometry, const complex::FloatVec3& translation)
```

2022-03-04 13:17 UTC, mmarineBlueQuartz commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +  GeometrySelectionParameter::AllowedTypes geomTypes{AbstractGeometry::Type::Any};
Unit tests will not pass using the empty set. It says the geometry is not the correct type.

2022-03-07 14:16 UTC, JDuffeyBQ requested changes

2022-03-07 14:16 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +    [[falthrough]] case complex::AbstractGeometry::Type::Quad:
```suggestion
    [[fallthrough]];
  case complex::AbstractGeometry::Type::Quad:
```
There's a missing "l" in the attribute. And I'd add a semicolon after the attribute to put it on it's own line. I think it makes it more readable, and it's how the example on cppreference is.

2022-03-07 15:06 UTC, JDuffeyBQ commented
The other `[[fallthrough]]` attributes need to fixed as well, but after that this PR should be good to go.

2022-03-07 20:06 UTC, JDuffeyBQ requested changes

2022-03-07 20:06 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +    [[falthrough]] case complex::AbstractGeometry::Type::Triangle:
```suggestion
    [[fallthrough]] case complex::AbstractGeometry::Type::Triangle:
```

2022-03-07 20:06 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp
> +    [[falthrough]] case complex::AbstractGeometry::Type::Tetrahedral:
```suggestion
    [[fallthrough]] case complex::AbstractGeometry::Type::Tetrahedral:
```

2022-03-16 13:55 UTC, JDuffeyBQ approved these changes

2022-03-16 13:57 UTC, merged