Feature/FindNeighbors
BlueQuartzSoftware/complex pull request #153
Opened 2022-03-15 11:54 UTC by mmarineBlueQuartz

* Added filter
* Added unit test
* Added documentation

2022-03-21 20:43 UTC, JDuffeyBQ requested changes

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighbors.cpp
> +} // namespace
```suggestion
```

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/FindNeighborsTest.cpp
> +inline const std::vector<std::string> k_CellFeatureNames{"Array 1", "Array 2", "Array 3"};
```suggestion
const std::string k_ImageGeomName = "Image Geom";
const std::string k_FeatureIdsName = "Feature IDs";
const std::string k_BoundaryCellsName = "Boundary Cells";
const std::string k_NumNeighborsName = "Num Neighbors";
const std::string k_NeighborListName = "Neighbor List";
const std::string k_SharedSurfaceAreaName = "Shared Surface Area";
const std::string k_SurfaceFeaturesName = "Surface Features";
const std::vector<std::string> k_CellFeatureNames{"Array 1", "Array 2", "Array 3"};
```

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/FindNeighborsTest.cpp
> +}
Needs a newline at end of file.

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/complex/DataStructure/AbstractDataStore.hpp
> +    Iterator(AbstractDataStore* dataStore, usize index)
```suggestion
    Iterator(AbstractDataStore& dataStore, usize index)
```
We can still use a reference in the signature of the constructor even if we store it as a pointer. I also think we should leave a comment that the iterator needs to be default constructible for some standard library algorithm implementations. And this change could be its own PR.

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/complex/DataStructure/AbstractDataStore.hpp
> +    ConstIterator(const AbstractDataStore* dataStore, usize index)
```suggestion
    ConstIterator(const AbstractDataStore& dataStore, usize index)
```
Same as the non-const one.

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/complex/Filter/Actions/CreateArrayAction.cpp
> +  case DataType::boolean: {
I must missed this in that PR. I can put in quick PR for it.

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighbors.cpp
> +      float area = float(number) * spacing[0] * spacing[1];
```suggestion
      float area = static_cast<float>(number) * spacing[0] * spacing[1];
```

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighbors.cpp
> +  int64 neighpoints[6] = {0, 0, 0, 0, 0, 0};
```suggestion
  std::array<int64, 6> neighpoints = {0, 0, 0, 0, 0, 0};
```

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighbors.cpp
> +  int64 dims[3] = {
```suggestion
  std::array<int64, 3> dims = {
```

2022-03-21 20:43 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighbors.cpp
> +  int64 column = 0, row = 0, plane = 0;
```suggestion
  int64 column = 0;
  int64 row = 0;
  int64 plane = 0;
```

2022-03-31 18:57 UTC, imikejackson submitted a review, later dismissed

2022-03-31 19:08 UTC, JDuffeyBQ requested changes

2022-03-31 19:08 UTC, JDuffeyBQ commented on src/complex/Filter/Actions/CreateArrayAction.cpp
> +, m_Type(static_cast<DataType>(type))
```suggestion
, m_Type(type)
```

2022-03-31 19:08 UTC, JDuffeyBQ commented on src/complex/DataStructure/AbstractDataStore.hpp
> +      if(!isValid() && !rhs.isValid())
What if only one is invalid?

2022-04-05 18:22 UTC, JDuffeyBQ approved these changes

2022-04-05 18:24 UTC, merged