Added MinNeighbors filter
BlueQuartzSoftware/complex pull request #154
Opened 2022-03-15 11:55 UTC by mmarineBlueQuartz

* Added filter
* Added unit test
* Added docs

2022-03-16 14:15 UTC, JDuffeyBQ requested changes

2022-03-16 14:15 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MinNeighbors.cpp
> +        for(const auto& arrayPath : voxelArrayPaths)
`getData` can potentially be expensive depending on the depth of the path, so the arrays should be acquired before the loops.

2022-03-16 14:15 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MinNeighbors.cpp
> +  data.validateNumberOfTuples(dataArrayPaths);
The return value is not checked.

2022-03-31 18:57 UTC, imikejackson submitted a review, later dismissed

2022-03-31 19:12 UTC, JDuffeyBQ requested changes

2022-03-31 19:12 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MinNeighbors.cpp
> +  DataStructure temp;
```suggestion
```

2022-04-05 18:29 UTC, JDuffeyBQ approved these changes

2022-04-05 18:39 UTC, merged