MultiThresholdObjects: Create BoolArray instead of UInt8Array
BlueQuartzSoftware/complex pull request #173
Opened 2022-03-28 14:29 UTC by imikejackson

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2022-03-28 17:08 UTC, JDuffeyBQ requested changes
All the uses of the mask array need to updated as well.

2022-03-28 20:54 UTC, joeykleingers approved these changes
Once Jared's changes get put in, this looks good.

2022-03-29 19:00 UTC, imikejackson commented
Do we know what filters have mask arrays?

2022-03-29 19:29 UTC, joeykleingers commented
Just from a cursory glance, here are all the filters that have masks with types that need to be changed to boolean:

FindSurfaceFeatures
MultiThresholdObjects
RobustAutomaticThreshold
ScalarSegmentFeaturesFilter

2022-03-31 19:08 UTC, joeykleingers requested changes

2022-03-31 19:08 UTC, joeykleingers commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp
> +      }
```suggestion
      tempResultVector.flip();
```

2022-03-31 19:08 UTC, joeykleingers commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp
> +      }
```suggestion
      tempResultVector.flip();
```

2022-03-31 19:23 UTC, joeykleingers submitted a review, later dismissed

2022-04-01 20:09 UTC, JDuffeyBQ requested changes

2022-04-01 20:09 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp
> +      (!newArrayPtr[i] ? newArrayPtr[i] = true : newArrayPtr[i] = false);
```suggestion
      newArrayPtr[i] = !newArrayPtr[i];
```

2022-04-01 20:09 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp
> +      (currentArray[i] || newArrayPtr[i]) ? currentArray[i] = true : currentArray[i] = false;
```suggestion
      currentArray[i] = currentArray[i] || newArrayPtr[i];
```

2022-04-05 16:48 UTC, JDuffeyBQ approved these changes

2022-04-05 16:58 UTC, merged