FILTER: ApplyTransformationToGeometry
BlueQuartzSoftware/complex pull request #181
Opened 2022-04-05 03:40 UTC by imikejackson

2022-04-05 15:08 UTC, mmarineBlueQuartz approved these changes

2022-04-05 18:26 UTC, JDuffeyBQ requested changes
There's an extra set of `ApplyTransformationToGeometry` files that are empty.

2022-04-06 13:31 UTC, mmarineBlueQuartz submitted a review, later dismissed

2022-04-06 14:57 UTC, JDuffeyBQ submitted a review, later dismissed

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +  REQUIRE(preflightResult.outputActions.valid());
```suggestion
  COMPLEX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +  REQUIRE(executeResult.result.valid());
```suggestion
  COMPLEX_RESULT_REQUIRE_VALID(executeResult.result);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(preflightResult.outputActions.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(executeResult.result.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(executeResult.result);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(preflightResult.outputActions.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(executeResult.result.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(executeResult.result);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(preflightResult.outputActions.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(preflightResult.outputActions.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(executeResult.result.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(executeResult.result);
```

2022-04-06 14:57 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/ApplyTransformationToGeometryFilterTest.cpp
> +    REQUIRE(executeResult.result.valid());
```suggestion
    COMPLEX_RESULT_REQUIRE_VALID(executeResult.result);
```

2022-04-07 16:26 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ApplyTransformationToGeometry.cpp
> +static std::map<size_t, int64_t> s_LastProgressInt;
It works just fine the way it is?

2022-04-08 19:25 UTC, mmarineBlueQuartz approved these changes

2022-04-08 21:13 UTC, merged