DataStore: Use memcpy for copy constructor.
BlueQuartzSoftware/complex pull request #186
Opened 2022-04-07 16:42 UTC by imikejackson

Also eliminates the need to copy the data manually in the deepCopy() function.

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2022-04-07 16:48 UTC, JDuffeyBQ requested changes

2022-04-07 16:48 UTC, JDuffeyBQ commented on src/complex/DataStructure/DataStore.hpp
> +#include <string.h>
```suggestion
#include <cstring>
```

2022-04-07 16:59 UTC, mmarineBlueQuartz requested changes

2022-04-07 16:59 UTC, mmarineBlueQuartz commented on src/complex/DataStructure/DataStore.hpp
>      auto size = this->getSize();
```suggestion
    return std::make_unique<DataStore<T>>(*this);
```

2022-04-07 19:40 UTC, imikejackson commented on src/complex/DataStructure/DataStore.hpp
> +
Removed the commented out code entirely.

2022-04-08 14:09 UTC, JDuffeyBQ approved these changes

2022-04-08 14:11 UTC, mmarineBlueQuartz approved these changes

2022-04-08 16:26 UTC, merged