Add numVerts static const to Vertex & Tetrahedral Geometries
BlueQuartzSoftware/complex pull request #194
Opened 2022-04-08 19:00 UTC by jmarquisbq

2022-04-08 19:35 UTC, mmarineBlueQuartz requested changes

2022-04-08 19:35 UTC, mmarineBlueQuartz commented on src/complex/DataStructure/Geometry/TetrahedralGeom.hpp
> +  static const int k_NumVerts = 4;
```suggestion
  static inline constexpr usize k_NumVerts = 4;
```
I don't think these are supposed to be different data types.

2022-04-08 22:46 UTC, imikejackson approved these changes

2022-04-11 14:17 UTC, mmarineBlueQuartz approved these changes

2022-04-12 12:26 UTC, merged