Add source_group() CMake code to adjust how the plugins are presented in Visual Studio
BlueQuartzSoftware/complex pull request #200
Opened 2022-04-14 22:19 UTC by imikejackson

2022-04-19 14:16 UTC, JDuffeyBQ requested changes

2022-04-19 14:16 UTC, JDuffeyBQ commented on src/PipelineRunner/CMakeLists.txt
> +)
Add newline for end of file.

2022-04-21 16:42 UTC, imikejackson commented on src/PipelineRunner/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/src/PRObserver.hpp
Done

2022-04-21 16:42 UTC, imikejackson commented on src/PipelineRunner/CMakeLists.txt
> +)
Done

2022-04-21 16:52 UTC, imikejackson commented on cmake/Plugin.cmake
> +
Fixed

2022-04-21 18:24 UTC, JDuffeyBQ requested changes

2022-04-21 18:24 UTC, JDuffeyBQ commented on cmake/Plugin.cmake
> +  source_group("Generated" FILES ${${ARGS_NAME}_GENERATED_HEADERS} )
```suggestion
  source_group("Generated" FILES ${${ARGS_NAME}_GENERATED_HEADERS})
```

2022-04-21 18:24 UTC, JDuffeyBQ commented on src/PipelineRunner/CMakeLists.txt
> +target_link_libraries(PipelineRunner complex::complex)
```suggestion
target_link_libraries(PipelineRunner PRIVATE complex::complex)
```

2022-04-22 13:26 UTC, JDuffeyBQ approved these changes

2022-04-22 16:14 UTC, merged