Move SegmentFeatures base class into complex
BlueQuartzSoftware/complex pull request #231
Opened 2022-05-27 19:23 UTC by imikejackson

This was done so that other filters can use this base class when they are stored in other plugins

2022-06-02 17:41 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/RotateSampleRefFrameTest.cpp
> -#include <catch2/catch.hpp>
Is this supposed to be here?

2022-06-02 18:21 UTC, jmarquisbq requested changes

2022-06-03 02:28 UTC, imikejackson commented on src/Plugins/ComplexCore/test/RotateSampleRefFrameTest.cpp
> -#include <catch2/catch.hpp>
The file has been completely removed.

2022-06-03 02:29 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ScalarSegmentFeaturesFilter.cpp
> +    return {nonstd::make_unexpected(std::vector<Error>{Error{-651, fmt::format("Input arrays do have matching tuple counts.")}})};
Opps. Fixed in latest push.

2022-06-06 15:42 UTC, JDuffeyBQ commented
If moving `RotateSampleRefFrame` is intended as part of this PR it should be documented.

2022-06-06 15:44 UTC, merged