Various API additions to support filter development
BlueQuartzSoftware/complex pull request #241
Opened 2022-06-22 14:38 UTC by imikejackson

* CropImageGeometry: Parallelize the array copying
* Segment Features: Add ability to cancel the segmentation loop. Clean up test code
* DataArrayUtilities: Added functions to support using Bool or UInt8 for Mask Arrays
* Create base class for AlignSections Algorithm.

2022-06-28 20:23 UTC, JDuffeyBQ requested changes
```cpp
/**
 * @brief TaskRunner runs a functor in a tbb::task_group if multicore is enabled.
 * It does not spawn more tasks than there are threads. Once the max thread count
 * is reached, the task group waits until all current tasks have been completed.
 * If multicore is not enabled, functors run sequentially. wait() must be called
 * before the object destructs.
 */
class TaskRunner
{
public:
  TaskRunner()
  : m_MaxThreadCount(std::thread::hardware_concurrency()) // std::thread::hardware_concurrency() returns ZERO if not defined on this platform
  {
  }

  TaskRunner(uint32 maxThreads)
  : m_MaxThreadCount(maxThreads)
  {
  }

  TaskRunner(const TaskRunner&) = delete;
  TaskRunner(TaskRunner&&) = delete;

  TaskRunner& operator=(const TaskRunner&) = delete;
  TaskRunner& operator=(TaskRunner&&) = delete;

  ~TaskRunner() = default;

  auto wait()
  {
#ifdef COMPLEX_ENABLE_MULTICORE
    return m_TaskGroup.wait();
#endif
  }

  template <class FunctorT>
  void run(FunctorT&& func)
  {
#ifdef COMPLEX_ENABLE_MULTICORE
    if(m_CurrentThreadCount == m_MaxThreadCount)
    {
      m_TaskGroup.wait();
      m_CurrentThreadCount = 0;
    }
    m_TaskGroup.run(std::forward<FunctorT>(func));
    m_CurrentThreadCount++;
#else
    func();
#endif
  }

private:
#ifdef COMPLEX_ENABLE_MULTICORE
  tbb::task_group m_TaskGroup;
  uint32 m_CurrentThreadCount = 0;
  uint32 m_MaxThreadCount = 1;
#endif
};
```
This should work for `CropImageGeometry` and `AlignSections`.

2022-06-29 18:23 UTC, JDuffeyBQ requested changes

2022-06-29 18:24 UTC, JDuffeyBQ requested changes

2022-06-29 18:24 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +
```suggestion
```

2022-06-29 18:59 UTC, imikejackson commented on src/complex/Utilities/DataArrayUtilities.cpp
> +  }
If that check isn't in there then the next line will throw an exception if the path is empty.  Thoughts?

2022-06-29 20:58 UTC, imikejackson commented on src/complex/Utilities/DataArrayUtilities.cpp
> +  }
I ended up putting a try.. catch block in the calling code instead.

2022-06-29 20:59 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +
Done in latest commit

2022-06-30 19:59 UTC, JDuffeyBQ approved these changes

2022-07-01 12:42 UTC, merged