Clang Tidy Mass Fixes
BlueQuartzSoftware/complex pull request #261
Opened 2022-07-22 18:50 UTC by imikejackson

* Default member initialization
* Range based loops from C++11

2022-07-22 18:51 UTC, imikejackson commented
Tried a few of these from the ITK source codes just to see what happens and what it picks up. @JDuffeyBQ let me know your thoughts.

2022-07-26 20:14 UTC, JDuffeyBQ requested changes

2022-08-10 12:54 UTC, jmarquisbq submitted a review, later dismissed

2022-08-10 15:35 UTC, JDuffeyBQ submitted a review, later dismissed

2022-08-10 15:35 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportHDF5Dataset.cpp
> +  for(auto dimsStr : dimsStrVec)
Instead of making this non-const ref, the output of `trimmed` can just be set to a new variable.

2022-08-12 13:36 UTC, JDuffeyBQ approved these changes

2022-08-21 14:45 UTC, merged