Added getTypeName function to NeighborList header to display type in hover info
BlueQuartzSoftware/complex pull request #270
Opened 2022-07-28 19:49 UTC by bpenniebq

2022-08-10 13:09 UTC, jmarquisbq commented on src/complex/DataStructure/Factory/NeighborListFactory.hpp
> +                            bool preflight) override
@bpenniebq Did we purposely get rid of the defaults for parentId and preflight in this function and readH5Dataset down below?

2022-08-10 14:33 UTC, jmarquisbq submitted a review, later dismissed

2022-08-10 20:41 UTC, imikejackson requested changes

2022-08-10 20:41 UTC, imikejackson commented on src/complex/DataStructure/Factory/NeighborListFactory.hpp
> +                              const std::optional<DataObject::IdType>& parentId, bool preflight) override
I think we should have the default arguments for parentId and preflight put back in. I'm sure it was just an oversight.

2022-08-11 14:32 UTC, imikejackson approved these changes

2022-08-11 14:32 UTC, merged