Geometry API: Rename methods to better convey what they do.
BlueQuartzSoftware/complex pull request #324
Opened 2022-10-03 14:25 UTC by imikejackson

The goal is to cut down on the confusion when writing codes that combine both the complex API and VTK APIs where the word "id" is both used to convey different meanings

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2022-10-04 12:32 UTC, jmarquisbq requested changes

2022-10-04 12:32 UTC, jmarquisbq commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/TriangleDihedralAngleFilter.cpp
>    if(faceAttributeMatrix == nullptr)
```suggestion
  if(triangleGeom == nullptr)
```

2022-10-06 16:56 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/TriangleDihedralAngleFilter.cpp
>    if(faceAttributeMatrix == nullptr)
Fixed in latest commits

2022-10-07 13:08 UTC, jmarquisbq approved these changes

2022-10-07 13:18 UTC, merged