Implement Output API for "Write" Filters
BlueQuartzSoftware/complex pull request #330
Opened 2022-10-18 14:07 UTC by nyoungbq

Requires a code review

This is the basis for a dependent PR in complex plugins

2022-10-19 17:54 UTC, JDuffeyBQ requested changes
Some of the suggestions can be applied in multiple places since I might not have found every case.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/StringUtilities.hpp
> +  if(std::is_floating_point_v<T>)
```suggestion
  if constexpr(std::is_floating_point_v<T>)
```
`if constexpr` will make sure this is only generated for floating point types.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +struct PrintMatrix2D
```suggestion
class PrintMatrix2D
```
Since this contains both public and private members, I'd change this to `class`. There is no difference in the code generated. It's a typical convention to use `struct` for objects that are all public.

Additionally is this part of the public API for these utilities? If not this and the associated classes below, could be moved into the cpp file.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +private:
We tend to put the private data at the bottom of the class and name member variables like `m_Rows`.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  size_t rows, columns;
```suggestion
  size_t m_Rows = 0;
  size_t m_Columns = 0;
```
Variable declarations are easier to read on multiple lines. Also generally we give member variables default values so we don't access uninitialized data accidentally. This is most important for primitive types because class types will call their default constructor like the `std::vector` below but primitive types do nothing.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  void checkBalanceType() // processor heavy, avoid running if you know its unbalanced
The stored `isBalanced` can get out of sync with the actual state of being balanced if `checkBalanceType` is not called.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  PrintMatrix2D& operator=(PrintMatrix2D&&) noexcept = default;
Since these are all default we can actually omit them and have the compiler automatically generate them. Part of it is a stylistic different though we should generally follow the "rule of 3/5/0" https://en.cppreference.com/w/cpp/language/rule_of_three

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  , matrix(numrows * numcols, std::string("UNINITIALIZED"))
```suggestion
  , matrix(numrows * numcols, "UNINITIALIZED")
```
The `std::string` isn't required, and we can directly pass in the string literal.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  LoadDataArrayToMatrixImpl(PrintMatrix2D& outputMatrix, const DataArray<T>& inputArray, const size_t& columnToWrite, bool hasHeaders = false)
```suggestion
  LoadDataArrayToMatrixImpl(PrintMatrix2D& outputMatrix, const DataArray<T>& inputArray, size_t columnToWrite, bool hasHeaders = false)
```
Primitives should be passed by value.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +    size_t row, column;
Since these variables are only used within the loops, they should be declared/defined in them.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  LoadStringArrayToMatrixImpl(PrintMatrix2D& outputMatrix, const StringArray& inputArray, const size_t& columnToWrite, bool hasHeaders = false)
```suggestion
  LoadStringArrayToMatrixImpl(PrintMatrix2D& outputMatrix, const StringArray& inputArray, size_t columnToWrite, bool hasHeaders = false)
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +      }
```suggestion
      for(size_t i = start; i < end; i++)
      {
        size_t row = i + 1;
        m_OutputMatrix.getValue(row, m_ColumnToWrite) = m_InputArray[i];
      }
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  const size_t& m_ColumnToWrite;
```suggestion
  size_t m_ColumnToWrite;
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +  const size_t& m_ColumnToWrite;
```suggestion
  size_t m_ColumnToWrite;
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +    m_StringStore[start] = std::move(sstrm.str());
```suggestion
    m_StringStore[start] = sstrm.str();
```
`std::stringstream::str()` returns a new `std::string` so `std::move` is not required.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +class COMPLEX_EXPORT OutputFunctions
Since there is not data, this can be made into a namespace and the private member functions can be moved to the cpp file as free functions. And then they should be renamed to match our free function naming/case convention.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +void OStreamUtilities::OutputFunctions::neighborListImplWrapper(DataStructure& dataStructure, PrintMatrix2D& matrixRef, DataObject::Type type, const DataPath& path, bool hasIndex, bool hasHeaders)
```suggestion
void OStreamUtilities::OutputFunctions::neighborListImplWrapper(const DataStructure& dataStructure, PrintMatrix2D& matrixRef, DataObject::Type type, const DataPath& path, bool hasIndex, bool hasHeaders)
```
`LoadNeighborListToMatrixImpl` takes a `NeighborList` by const ref so `DataStructure` should be passed by const ref also.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +  if(type == DataObject::Type::INeighborList) // unique because its loaded horizontally no dataAlg use
This `if` should be an early return instead. It will help readability by helping to avoid too much nesting.
```cpp
if(type != DataObject::Type::NeighborList)
{
  throw std::runtime_error("OStreamUtilities::OutputFunctions::neighborListImplWrapper can only process neighborLists")
}
```
Additionally it should use `DataObject::Type::NeighborList` because `DataObject::Type::INeighborList` will never be used. All `NeighborList` classes override `getDataObjectType`.

Unrelated to this PR, but those base class enums really should be removed or we should change how we check for derived types to avoid issues like this. @imikejackson

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +    }
```suggestion
    const auto& iNeighborList = dataStructure.getDataRefAs<INeighborList>(path);
    auto dataType = iNeighborList.getDataType();
    switch(dataType)
    {
    case DataType::int8: {
      const auto& neighborList = dynamic_cast<const NeighborList<int8>&>(iNeighborList);
      LoadNeighborListToMatrixImpl(matrixRef, neighborList, hasIndex, hasHeaders).loadToMatrix(0, neighborList.getSize());
      break;
    }
```
This should store the neighbor list to avoid having to check the data structure multiple times. And since we know we have a `INeighborList` we can use `getDataRefAs`. This can be repeated for this rest of the cases.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +void OStreamUtilities::OutputFunctions::dataAlgParallelWrapper(DataStructure& dataStructure, PrintMatrix2D& matrixRef, DataObject::Type type, const DataPath& path, const size_t& column,
The same change from `OStreamUtilities::OutputFunctions::neighborListImplWrapper` can be made in this function.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +    auto grain = list.getListReference(i);
```suggestion
    const auto& grain = list.getListReference(i);
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +size_t getMaxNeighborlistElements(NeighborList<T> list)
```suggestion
size_t getMaxNeighborlistElements(const NeighborList<T>& list)
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +      }
```suggestion
      T value = grain[index];
      if(value > max)
      {
        max = value ;
      }
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +          auto grain = m_InputArray.getListReference(i);
```suggestion
          const auto& grain = m_InputArray.getListReference(i);
```
In this case, `auto` would be a plain `std::vector<T>` which would make a copy. In general it is important to specify the const-ness and whether it is a pointer or reference when using `auto` to avoid accidental copies.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +          auto grain = m_InputArray.getListReference(i);
```suggestion
          const auto& grain = m_InputArray.getListReference(i);
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +          auto grain = m_InputArray.getListReference(i);
```suggestion
          const auto& grain = m_InputArray.getListReference(i);
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.hpp
> +          auto grain = m_InputArray.getListReference(i);
```suggestion
          const auto& grain = m_InputArray.getListReference(i);
```

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +  auto count = 0;
```suggestion
  usize count = 0;
```
`auto` with literals can be tricky. In this case, the literal is `int`, but since since this is a count for `std::vector`, `size_t`/`usize` is more appropriate.

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +  bool hasNeighborLists = false;
Is this used?

2022-10-19 17:54 UTC, JDuffeyBQ commented on src/complex/Utilities/OStreamUtilities.cpp
> +void OStreamUtilities::OutputFunctions::neighborListImplWrapper(DataStructure& dataStructure, PrintMatrix2D& matrixRef, DataObject::Type type, const DataPath& path, bool hasIndex, bool hasHeaders)
It might be good to wrap these functions inside their respective namespace in order to cut down on line length and make it more readable.

2022-10-28 13:38 UTC, imikejackson commented
The API is taking too long inside of the PrintMatrix2D::getBalance method. See attachment for a time stack trace. I had to quit DREAM3D as the filter never wrote anything after a few minutes. We will need to further look into the performance of the new API.

![Screen Shot 2022-10-28 at 09 36 35](https://user-images.githubusercontent.com/5182396/198615847-9eaf5572-0e40-4d86-b527-1575eb628ba0.png)

2022-10-28 14:19 UTC, nyoungbq commented
> The API is taking too long inside of the PrintMatrix2D::getBalance method. See attachment for a time stack trace. I had to quit DREAM3D as the filter never wrote anything after a few minutes. We will need to further look into the performance of the new API.
> 
> ![Screen Shot 2022-10-28 at 09 36 35](https://user-images.githubusercontent.com/5182396/198615847-9eaf5572-0e40-4d86-b527-1575eb628ba0.png)

I can just strip the get balance method out completely, It was just there to try to speed things up during the print so I doesn't have to check for the "UNINITIALIZED" string.

2022-11-09 14:15 UTC, closed without merging