Feature/filter comments
BlueQuartzSoftware/complex pull request #351
Opened 2022-11-08 16:04 UTC by jmarquisbq

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files.

- [ ] Class and Structs are `UpperCamelCase`
- [ ] Class private member variables are `m_UpperCamelCase`
- [ ] Class methods are `lowerCamelCase`
- [ ] Method arguments are `lowerCamelCase`
- [ ] Normal variables are `lowerCamelCase`
- [ ] Constants are `k_UpperCamelCase`
- [ ] Global statics are `s_UpperCamelCase`
- [ ] Free Functions are `UpperCamelCase`
- [ ] Macros are `ALL_UPPER_SNAKE_CASE`
- [ ] Unit test will test data output from the filter.
- [ ] Reused strings should be constants in an anonymous namespace
- [ ] If parallelization is used, proper use of the abstracted complex classes are used. Using TBB specifically in a filter should be frowned upon unless for a really good reason.

## Filter Checklist

- [ ] Parameters should be generally broken down into "Input Parameters", "Required Data Objects", "Created Data Objects". There can be exceptions to this.
- [ ] ChoicesParameter selections should be an enumeration defined in the filer header
- [ ] Documentation copied from SIMPL Repo and updated (if necessary)
- [ ] Parameter argument variables are k_CamelCase_Key
- [ ] Parameter argument strings are lower_snake_case
```
static inline constexpr StringLiteral k_AlignmentType_Key = "alignment_type";
```

## Unit Testing
- [ ] 1 Unit test to instantiate the filter with the default arguments.
- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] Filters should have both the Filter class and Algorithm class for anything beyond trivial needs
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added Python wrapping to new files (if any) as necessary
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented.

2022-11-09 15:14 UTC, JDuffeyBQ reviewed
I think comments would be better suited in `PipelineFilter`. This would avoid having to manually add a comment parameter to every filter. And comments are not input to a filter so using a different holder would make more sense.

2022-11-11 04:32 UTC, JDuffeyBQ requested changes
Do we want a separator with "Input Parameters" on every filter? If so, we could add that to the NX layout by default.

2022-11-11 04:32 UTC, JDuffeyBQ commented on src/complex/Pipeline/PipelineFilter.hpp
> +  std::string getComments() const;
```suggestion
  const std::string& getComments() const;
```

2022-11-14 15:13 UTC, joeykleingers approved these changes

2022-11-16 17:13 UTC, merged