ENH: OStreamUtilites API
BlueQuartzSoftware/complex pull request #353
Opened 2022-11-09 18:55 UTC by nyoungbq

The API for all primary std::ostream child classes. It has capability for printing every child of IArray. Ready for code review.

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files.

- [ ] Class and Structs are `UpperCamelCase`
- [ ] Class private member variables are `m_UpperCamelCase`
- [ ] Class methods are `lowerCamelCase`
- [ ] Method arguments are `lowerCamelCase`
- [ ] Normal variables are `lowerCamelCase`
- [ ] Constants are `k_UpperCamelCase`
- [ ] Global statics are `s_UpperCamelCase`
- [ ] Free Functions are `UpperCamelCase`
- [ ] Macros are `ALL_UPPER_SNAKE_CASE`
- [ ] Unit test will test data output from the filter.
- [ ] Reused strings should be constants in an anonymous namespace
- [ ] If parallelization is used, proper use of the abstracted complex classes are used. Using TBB specifically in a filter should be frowned upon unless for a really good reason.

## Filter Checklist

- [ ] Parameters should be generally broken down into "Input Parameters", "Required Data Objects", "Created Data Objects". There can be exceptions to this.
- [ ] ChoicesParameter selections should be an enumeration defined in the filer header
- [ ] Documentation copied from SIMPL Repo and updated (if necessary)
- [ ] Parameter argument variables are k_CamelCase_Key
- [ ] Parameter argument strings are lower_snake_case
```
static inline constexpr StringLiteral k_AlignmentType_Key = "alignment_type";
```

## Unit Testing
- [ ] 1 Unit test to instantiate the filter with the default arguments.
- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] Filters should have both the Filter class and Algorithm class for anything beyond trivial needs
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added Python wrapping to new files (if any) as necessary
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented.

2022-11-09 18:59 UTC, nyoungbq commented
Also stripped out BoolNeighborList typing as it is non-functional with current implementation

2022-11-09 19:03 UTC, nyoungbq commented
The unit testing for this API comes in the form of the WriteXXXXDataFilters in the dependent PR in complex plugins

2022-11-10 19:30 UTC, imikejackson requested changes

2022-11-10 19:30 UTC, imikejackson commented on src/complex/Utilities/DataArrayUtilities.hpp
> +/**
Finish this documentation blurb.

2022-11-10 19:30 UTC, imikejackson commented on src/complex/Utilities/OStreamUtilities.cpp
> +                                  const std::atomic_bool& shouldCancel, std::string fileExtension, bool exportToBinary, const std::string& delimiter, bool includeIndex, bool includeHeaders,
fileExtension should be passed by const reference

2022-11-10 19:30 UTC, imikejackson commented on src/complex/Utilities/OStreamUtilities.cpp
> +                               const std::atomic_bool& shouldCancel, const std::string& delimiter, bool includeIndex, bool includeHeaders, size_t componentsPerLine,
componentsPerLine is never used. Maybe we should remove it from the argument list

2022-11-10 19:30 UTC, imikejackson commented on src/complex/Utilities/OStreamUtilities.cpp
> +  if(neighborLists.size() != 0)
```suggestion
  if(!neighborLists.empty())
```

2022-11-11 00:51 UTC, imikejackson approved these changes

2022-11-11 00:52 UTC, merged