FILTER: ImportVolumeGraphicsFile
BlueQuartzSoftware/complex pull request #395
Opened 2022-12-26 14:43 UTC by joeykleingers

Signed-off-by: Joey Kleingers <joey.kleingers@bluequartz.net>

2022-12-27 19:55 UTC, imikejackson requested changes

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +inline const std::string k_Datatype("Datatype");
I think we settled on k_CamelCase for constant variables

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +static inline constexpr int32 k_FileDoesNotExist = -91501;
static is redundant inside an anonymous namespace

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +  std::string status = "visible";
We should be consistent about case inside of structs. This one has 'lowerCame' and the struct above has mixed lowerCamel and UpperCamel

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +  std::string Name = "AS_N610_02.vol";
This should be initialized to an empty string.

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +
validate that there are enough tokens instead of throwing the exception (for out of range)

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +
Same token length check here also. It will help simplify the code

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +
Same token length check

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +
Token length check

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +  fs::path vgiDataFilePath;
make case consistent with other structs in this file

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +static std::atomic_int32_t s_InstanceId = 0;
static is redundant for anonymous namespace

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +  return {"#IO", "#Input", "#Read", "#Import"};
Add #CT #VolumeGraphics #vgi

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +  params.insert(std::make_unique<FileSystemPathParameter>(k_VGHeaderFile_Key, "VolumeGraphics .vgi File", "", fs::path("DefaultInputFileName"), FileSystemPathParameter::ExtensionsType{".vgi"},
Need the help text filled in. These are used for the Python documentation so they help. It may seem obvious.. .but..

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +
Break up the parameters such that generally you have:
params.insertSeparator(Parameters::Separator{"Parameters"});

params.insertSeparator(Parameters::Separator{"Input Data"});

params.insertSeparator(Parameters::Separator{"Created Data"});

You can embellish those if the code calls for it and would ultimately help the user.

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ImportVolumeGraphicsFile.cpp
> +inline constexpr int32 k_VolBinaryAllocateMismatch = -91504;
I think these should just be `inline const int32`. By using an anonymous namespace we don't need static and constexpres should generally not be used inside of an anonymous namespace. Which if that is the case then there are a whole bunch of filters that need to be updated

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ImportVolumeGraphicsFile.cpp
> +inline constexpr int32 k_VolReadError = -91506;
if we are going to be using `usize` then we should be using `int32` instead of `int32_t`

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ImportVolumeGraphicsFile.hpp
> +  std::filesystem::path VGDataFile;
You should inlcude the <filesystem> header if you are using std::filesystem in the header. Along with <string> and strip out includes that are not directly being used in this header like ArrayCreationParameter.hpp

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +#include "Algorithms/ImportVolumeGraphicsFile.hpp"
This should be the complete path to the Algorithms folder. so ComplexCore/Filters/Algorithms/.....

2022-12-27 19:55 UTC, imikejackson commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportVolumeGraphicsFileFilter.cpp
> +#include <fstream>
Group the C++ STL includes after all other includes

2023-02-01 17:52 UTC, nyoungbq approved these changes

2023-02-01 17:53 UTC, merged