Added BaseGroup::findAllChildrenOfType utility method
BlueQuartzSoftware/complex pull request #43
Opened 2021-11-12 14:49 UTC by mmarineBlueQuartz

* Added to DataStructure unit tests

2022-02-10 04:45 UTC, imikejackson approved these changes
Rebase on develop and merge

2022-02-18 16:25 UTC, JDuffeyBQ requested changes

2022-02-18 16:25 UTC, JDuffeyBQ commented on src/complex/DataStructure/BaseGroup.hpp
> +      if(recursive == true)
```suggestion
      if(recursive)
```

2022-02-18 16:25 UTC, JDuffeyBQ commented on src/complex/DataStructure/BaseGroup.hpp
> +      if(auto typePtr = std::dynamic_pointer_cast<T>(ptr))
```suggestion
      if(auto typePtr = std::dynamic_pointer_cast<T>(ptr); typePtr != nullptr)
```

2022-02-18 16:25 UTC, JDuffeyBQ commented on src/complex/DataStructure/BaseGroup.hpp
> +        if(auto groupPtr = std::dynamic_pointer_cast<BaseGroup>(ptr))
```suggestion
        if(auto groupPtr = std::dynamic_pointer_cast<BaseGroup>(ptr); groupPtr != nullptr)
```

2022-02-18 21:22 UTC, JDuffeyBQ approved these changes

2022-02-18 21:55 UTC, merged