Array operations added [WIP]
BlueQuartzSoftware/complex pull request #432
Opened 2023-01-25 15:21 UTC by VKUDRI

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `complex/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `complex/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

2023-01-31 17:51 UTC, JDuffeyBQ requested changes
How much are we doing with the matrix class? I'd want to avoid turning it into Eigen.

2023-01-31 17:51 UTC, JDuffeyBQ commented on src/complex/Common/Array.hpp
> +  inline T magnitude()
```suggestion
  inline T magnitude() const
```

2023-01-31 17:51 UTC, JDuffeyBQ commented on src/complex/Common/Array.hpp
> +  }
Split comma operator usage into multiple lines.

2023-01-31 17:51 UTC, JDuffeyBQ commented on src/complex/Common/Array.hpp
> +  }
For primitive type `T`, pass by value.

2023-02-13 17:21 UTC, imikejackson commented on src/complex/Common/Array.hpp
> +  inline T magnitude()
There are some very basic vector3 operations that complex/dream3d tend to do and this is one of them so I'll let this through.

2023-02-13 17:23 UTC, imikejackson commented on src/complex/Common/Array.hpp
> +  }
Done

2023-02-13 17:23 UTC, imikejackson commented on src/complex/Common/Array.hpp
> +  }
Done

2023-02-13 19:14 UTC, imikejackson approved these changes

2023-02-13 19:16 UTC, merged

2023-02-13 19:33 UTC, JDuffeyBQ commented
Are we keeping the matrix classes?