ENH: Updated CLI interface
BlueQuartzSoftware/complex pull request #446
Opened 2023-02-14 17:25 UTC by mmarineBlueQuartz

## Changes:

* Renamed PipelineRunner to NX-cli.
* Restructured parsing for parameters.
  * Changed syntax for preflight and execute.
  * Added syntax for help.
* Renamed namespace from PipelineRunner to CLI

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `complex/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `complex/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [x] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added license to new files (if any)
- [x] Added example pipelines that use the filter
- [x] Classes and methods are properly documented

2023-03-07 19:12 UTC, joeykleingers requested changes

2023-03-07 19:12 UTC, joeykleingers commented on src/DREAM3DNX-cli/src/DREAM3DNX_cli.cpp
> +  return {args};
Unless I'm missing it, this algorithm should have a default case that handles when the argument is unrecognized/unexpected.  For example, if argc = 2 and argv = [executable_path, "--blah"], then this code will go all the way through without setting args to anything or erroring out, and then will return empty args.

2023-03-07 19:12 UTC, joeykleingers commented on src/DREAM3DNX-cli/src/DREAM3DNX_cli.cpp
> +  std::cout << fmt::format("\t {} <filepath>\t", k_ExecuteParamLong) << "\t Execute the pipeline at the taget filepath\n";
```suggestion
  std::cout << fmt::format("\t {} <filepath>\t", k_ExecuteParamLong) << "\t Execute the pipeline at the target filepath\n";
```

2023-03-07 19:12 UTC, joeykleingers commented on src/DREAM3DNX-cli/src/DREAM3DNX_cli.cpp
> +  std::cout << fmt::format("\t {} <filepath>\t", k_ExecuteParamShort) << "\t Execute the pipeline at the taget filepath\n";
```suggestion
  std::cout << fmt::format("\t {} <filepath>\t", k_ExecuteParamShort) << "\t Execute the pipeline at the target filepath\n";
```

2023-03-07 19:12 UTC, joeykleingers commented on src/DREAM3DNX-cli/src/DREAM3DNX_cli.cpp
> +  std::cout << fmt::format("\t {} <filepath>\t", k_PreflightParamLong) << "\t Preflight the pipeline at the taget filepath" << std::endl;
```suggestion
  std::cout << fmt::format("\t {} <filepath>\t", k_PreflightParamLong) << "\t Preflight the pipeline at the target filepath" << std::endl;
```

2023-03-07 19:12 UTC, joeykleingers commented on src/DREAM3DNX-cli/src/DREAM3DNX_cli.cpp
> +  std::cout << fmt::format("\t {} <filepath>\t", k_PreflightParamShort) << "\t Preflight the pipeline at the taget filepath" << std::endl;
```suggestion
  std::cout << fmt::format("\t {} <filepath>\t", k_PreflightParamShort) << "\t Preflight the pipeline at the target filepath" << std::endl;
```

2023-03-09 17:17 UTC, imikejackson commented
@mmarineBlueQuartz I would also like to have the option "--logfile" so that all output can be redirected to a file.

2023-04-10 20:48 UTC, imikejackson commented
in the context of the flow of events, if possible, I would recommend that the arguments are all figured out, then the plugins are loaded and the pipeline executed. 

Take a look at my changes/additions and see what you think

2023-04-13 21:04 UTC, imikejackson approved these changes

2023-04-17 13:09 UTC, imikejackson approved these changes

2023-04-19 18:06 UTC, imikejackson approved these changes

2023-04-21 15:29 UTC, merged