Fitler:surface nets 3D
BlueQuartzSoftware/complex pull request #577
Opened 2023-05-03 14:56 UTC by imikejackson

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `complex/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `complex/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

2023-05-05 17:28 UTC, imikejackson commented
There are a number of issues with this initial implementation: 
+ The actual coordinate values generated for each vertex is based off of an origin of 0,0,0. We can either update the codes to take the real origin of the input Image Geometry into account, or just apply the proper translation to the final vertices at the end of the algorithm
+ The code only accepts uint16 at this point and needs to be converted to int32 at the minimum. Having a templated version to handle any `integer` type would be fantastic
+ The codes will allocate arrays in old C-Style and uses an Array-of-Structs (AoS) type of allocation. This should be rewritten to use individual arrays for each property in the MMCell class. 
+ I think a 2 pass approach could be used to figure out how many vertices and how many triangles are going to be created. This will save a whole bunch of memory allocations during the actual filter itself.
+ The node types need to be figured out to have better compatibility with existing DREAM.3D Filters.


Filters that use NodeType:
+ SurfaceMeshToVtk
+ SurfaceMeshToNonconformalVtk
+ FindGBCDMetricBased
+ FindGBPDMetricBased
+ LaplacianSmoothing
+ BInaryNodesTriangleReader
+ ExtractInternalSurfacesFromTriangleGeometry
+ ExtractTripleLinesFromTriangleGeometry

2023-05-09 18:09 UTC, mmarineBlueQuartz requested changes

2023-05-09 18:09 UTC, mmarineBlueQuartz commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/SurfaceNets.cpp
> +  auto& featureIdDataStore = featureIds.getIDataStoreRefAs<Int32DataStore>();
```suggestion
  auto& featureIdDataStore = featureIds.getDataStoreRef();
```
Using `getDataStoreRef()` returns an `AbstractDataStore<T>&` that is expandable to other forms of data storage. If you do not require `DataStore<T>`'s `data()` method, there is no need to force the use of an in-memory implementation.

2023-06-20 21:24 UTC, imikejackson commented
replaced by #619

2023-06-20 21:24 UTC, closed without merging