Handle DataStructure::makePath errors
BlueQuartzSoftware/complex pull request #624
Opened 2023-06-27 16:36 UTC by mmarineBlueQuartz

Removes created DataPaths if DataStructure::makePath causes an error.

Fixes #127

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `complex/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `complex/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

2023-06-27 17:21 UTC, nyoungbq approved these changes

2023-07-02 19:43 UTC, imikejackson requested changes

2023-07-02 19:43 UTC, imikejackson commented on src/complex/DataStructure/DataStructure.cpp
> +        return complex::MakeErrorResult<LinkedPath>(-3, "Target parent object in path is not derived from BaseGroup.");
Please incorporate the "path" argument into the error message. This will help the user/developer better diagnose what is going wrong.

2023-07-02 19:43 UTC, imikejackson commented on src/complex/DataStructure/DataStructure.cpp
>      return complex::MakeErrorResult<LinkedPath>(-2, "Exception thrown when attempting to create a path in the DataStructure");
Please also incorporate that actual value of 'path' into the error message. If there are ways to better determine the type of exception thrown that would also help in the error message.

2023-07-06 13:59 UTC, nyoungbq commented on src/complex/DataStructure/DataStructure.cpp
> +        return complex::MakeErrorResult<LinkedPath>(-3, "Target parent object in path is not derived from BaseGroup.");
```suggestion
        return complex::MakeErrorResult<LinkedPath>(-3, fmt::format("Target parent object {} in path {} is not derived from BaseGroup.", name, path.toString()));
```

2023-07-06 13:59 UTC, nyoungbq commented on src/complex/DataStructure/DataStructure.cpp
>      return complex::MakeErrorResult<LinkedPath>(-2, "Exception thrown when attempting to create a path in the DataStructure");
```suggestion
    return complex::MakeErrorResult<LinkedPath>(-2, fmt::format("Exception thrown when attempting to create a path in the DataStructure: {}", e.what()));
```

2023-07-06 17:03 UTC, nyoungbq approved these changes

2023-07-06 19:27 UTC, merged