MultiThresholdObjects: Add ability to set custom TRUE and FALSE values.
BlueQuartzSoftware/complex pull request #669
Opened 2023-08-18 14:42 UTC by joeykleingers

2023-08-18 19:02 UTC, JDuffeyBQ requested changes

2023-08-18 19:02 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp
> +  if(useCustomTrueValue)
We should have a check to prevent selecting custom true/false values if the output mask array uses bools.

2023-08-18 19:02 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/test/MultiThresholdObjectsTest.cpp
> +    auto* thresholdArray = dataStructure.getDataAs<UInt8Array>(k_ThresholdArrayPath);
I think that we should keep a bool mask array in addition to the custom values test to cover all options.

2023-08-19 02:03 UTC, imikejackson commented on src/Plugins/ComplexCore/test/MultiThresholdObjectsTest.cpp
> +    auto* thresholdArray = dataStructure.getDataAs<UInt8Array>(k_ThresholdArrayPath);
I agree.

2023-08-19 02:04 UTC, imikejackson commented
The documentation MUST be updated to include something to the effect that if you chose custom values for true/false this will break other filters that rely on a 0/1 for true/false.

@joeykleingers Please make sure the documentation is updated.

2023-08-22 20:46 UTC, JDuffeyBQ approved these changes

2023-08-22 20:51 UTC, merged