ENH: Add More Resampling Modes To Resample Image Geometry
BlueQuartzSoftware/complex pull request #689
Opened 2023-09-05 16:53 UTC by joeykleingers

+ Added "Scaling" and "Exact Dimensions" modes along with the default "Spacing" mode.

2023-09-05 16:54 UTC, joeykleingers commented
NOTE: The DataArchive must be updated with a new test .tar.gz file right after this PR is merged in!

2023-09-12 15:35 UTC, imikejackson requested changes
Can you also create an example pipeline that shows the usage of each kind of resampling. Just use one of the "Porosity" images and an example. Does not have to be fancy image.

2023-09-12 15:35 UTC, imikejackson commented on src/Plugins/ComplexCore/docs/ResampleImageGeomFilter.md
> +The values entered are the desired scaling factor for each dimension, in percentages.  (50%, 50%, 50%) would resample the geometry by half in all dimensions.
Can you give a more concrete example by stating for a given scaling and dimensions, if I put in 50% in all directions, what do I end up with for dimensions and scaling.

2023-09-12 15:35 UTC, imikejackson commented on src/Plugins/ComplexCore/docs/ResampleImageGeomFilter.md
> +The values entered are the desired new spacings (not multiples of the current resolution).  The number of **Cells** in the volume will change when the spacing values are changed and thus the user sho
Give a concrete example using example dimensions and scaling.

2023-09-12 15:35 UTC, imikejackson commented on src/Plugins/ComplexCore/docs/ResampleImageGeomFilter.md
> +The values entered are the desired cell dimensions of the resampled geometry.  (100, 100, 100) would resample the geometry so that there are 100 cells in each dimension.
How would this effect the scaling values in each direction. Give a concrete example.

2023-09-13 15:18 UTC, imikejackson approved these changes

2023-09-13 16:27 UTC, merged