Import CSV Data Redesign
BlueQuartzSoftware/complex pull request #706
Opened 2023-09-29 13:27 UTC by joeykleingers

* Updated the parameter to only include the data required for the filter, removing unnecessary fields and make sure that all fields can be converted easily with the Python bindings.
* Updated the filter to do additional error checking and cache the file's total lines and headers to avoid reading the entire file every preflight.
* Moved the DynamicTableData tuple dimensions parameter into the CSVImporterData custom parameter.
* Removed all references to "wizard", since the UI no longer involves using a wizard.
* Updated the Python bindings to expose the new CSVImporterData struct to Python.
* Updated the Import CSV Data unit test and any other unit tests that use the filter.
* Updated the regular filter documentation as well as the Python documentation.

2023-10-03 16:58 UTC, JDuffeyBQ requested changes

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/complex/Utilities/FileUtilities.hpp
> +  } catch(std::exception& e)
```suggestion
  } catch(const std::exception& e)
```

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/complex/Utilities/FileUtilities.hpp
> +  in.close();
```suggestion
```
Not need because it's already handled by the `std::fstream` destructor.

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/complex/Utilities/FileUtilities.hpp
> +  std::fstream in(absPath.c_str(), std::ios_base::in | std::ios_base::binary);
```suggestion
  std::ifstream in(absPath.c_str(), std::ios_base::binary);
```

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportCSVDataFilter.cpp
> +  usize numTuples = std::accumulate(csvImporterData.tupleDims.begin(), csvImporterData.tupleDims.end(), 1, std::multiplies<>());
```suggestion
  usize numTuples = std::accumulate(csvImporterData.tupleDims.cbegin(), csvImporterData.tupleDims.cend(), static_cast<usize>(1), std::multiplies<>());
```
Unfortunately there's a warning that keeps cropping up where `std::accumulate` and other standard library functions deduce the wrong return type if you don't static cast the initial value.

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportCSVDataFilter.cpp
> +    numTuples = std::accumulate(am.getShape().begin(), am.getShape().end(), 1, std::multiplies<>());
```suggestion
    numTuples = std::accumulate(am.getShape().cbegin(), am.getShape().cend(), static_cast<usize>(1), std::multiplies<>());
```

2023-10-03 16:58 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportCSVDataFilter.cpp
> +IFilter::PreflightResult ImportCSVDataFilter::readHeaders(const std::string& inputFilePath, usize headersLineNum, bool useTab, bool useSemicolon, bool useSpace, bool useComma,
This function could take the header cache as an argument instead of being a member function.

2023-10-03 17:48 UTC, JDuffeyBQ approved these changes

2023-10-04 15:38 UTC, JDuffeyBQ commented
It's probably a good idea to add a unit test for the blank line handling.

2023-10-05 14:43 UTC, joeykleingers commented
@JDuffeyBQ Blank lines test has been added.  Approve unless there's anything else you'd like fixed/changed.

2023-10-05 14:45 UTC, joeykleingers commented
Actually, hang on... let me add one more test that checks to make sure that the filter handles unexpected inputs for the other arguments.  Like if the user inputs 0 for the start row or a number larger than the total file size for the header row, for example.

2023-10-05 16:22 UTC, joeykleingers commented
@JDuffeyBQ Last unit test has been added.  Ready for review again.

2023-10-11 13:27 UTC, JDuffeyBQ commented
I don't have a good suggestion but we have a similarly named filter in ImportTextFilter so I think that they should be easier to distinguish.

2023-10-11 14:56 UTC, imikejackson commented
These need renamed:

[ ] ImportTextFilter -> ReadTextDataArrayFilter
[ ] ImportTextDataFilter -> ReadCSVFileFilter

[ ] Rename the parameter from `ImportTextDataParameter` to `ReadCSVFileParameter`

[ ] TextImporterData::writeJson convert the delimiters to a std::vector<std::string> BEFORE writing
[ ] TextImporterData::readJson convert from std::vector<std::string> to std::vector<char> after reading in from the JSON file.

2023-10-11 18:38 UTC, joeykleingers commented
@imikejackson All of the most recent suggestions have been implemented.  This is ready for final review and approval.

2023-10-12 16:46 UTC, imikejackson approved these changes

2023-10-12 18:46 UTC, merged