PY: Added Python Code for Most Example Pipelines
BlueQuartzSoftware/complex pull request #800
Opened 2023-12-15 21:41 UTC by ajacksonbq

2024-01-09 17:18 UTC, imikejackson approved these changes

2024-01-09 17:58 UTC, JDuffeyBQ requested changes
Some pipelines still need a new line at the end of the file. Aside from that looks good.

2024-01-09 17:58 UTC, JDuffeyBQ commented on src/Plugins/ITKImageProcessing/tools/itk_filter_generator.py
> +    auto nx_filter = FilterType::New();{setters_str}
```suggestion
    auto filter = FilterType::New();{setters_str}
```
Looks like this accidentally got caught by the renaming.

2024-01-12 22:02 UTC, imikejackson approved these changes

2024-01-12 22:03 UTC, imikejackson commented
> Some pipelines still need a new line at the end of the file. Aside from that looks good.

All have been corrected.

2024-01-12 22:10 UTC, imikejackson approved these changes

2024-01-14 17:34 UTC, merged