Added CropImageGeometry filter
BlueQuartzSoftware/complex pull request #87
Opened 2022-02-01 13:43 UTC by mmarineBlueQuartz

* Added CropImageGeometry filter
* Added SamplingUtils
* Added unit test

2022-02-02 20:05 UTC, JDuffeyBQ requested changes

2022-02-02 20:05 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +  auto oldResolution = getCurrentVolumeDataContainerResolutions(data, srcImagePath);
The comment indicates that these are required, but the functions don't have a way to report errors.

2022-02-02 20:05 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +    auto* srcImageGeom = data.getDataAs<ImageGeom>(srcImagePath);
This line shadows the variable on line 235 and looks like it's getting the same geometry anyway.

2022-02-02 20:05 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +    std::vector<usize> cDims = {1};
Is this meant to be used to check the number of components for the following array?

2022-02-02 20:05 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +  auto* destImageGeom = data.getDataAs<ImageGeom>(destImagePath);
```suggestion
  auto& srcImageGeom = data.getDataRefAs<ImageGeom>(srcImagePath);
  auto& destImageGeom = data.getDataRefAs<ImageGeom>(destImagePath);
```

2022-02-03 14:41 UTC, imikejackson requested changes
Not much more to say past what @JDuffeyBQ has stated. Ensure the unit test for this works or we have bench marked this against the current version in SIMPL/DREAM.3D

The "RenumberFeatures" should also be generic enough that other filters can use it. I'm pretty sure that a handful of filters in SIMPL/DREAM.3D need this functionality.

2022-02-15 18:56 UTC, JDuffeyBQ reviewed
This will need a minor update for the cancellation changes.

2022-02-16 16:44 UTC, JDuffeyBQ approved these changes

2022-02-18 16:26 UTC, JDuffeyBQ submitted a review, later dismissed

2022-02-23 21:14 UTC, imikejackson commented
Is this ready to go? Not seen any activity. @mmarineBlueQuartz

2022-02-23 21:15 UTC, imikejackson commented
Also make sure to bring over the documentation file (plus any references images) from current DREAM3D

2022-03-01 19:48 UTC, JDuffeyBQ requested changes

2022-03-01 19:48 UTC, JDuffeyBQ commented on src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp
> +std::string getOldBoxDimensions(const DataStructure& dataStructure, const DataPath& imageGeomPath)
These two functions aren't used right now, but in the original the were used for the preflight updated value.

2022-03-07 20:29 UTC, JDuffeyBQ approved these changes

2022-03-11 15:47 UTC, imikejackson approved these changes

2022-03-11 15:48 UTC, merged