ENH: Implement Feret/Caliper distance metrics in Find Feature Sizes.
BlueQuartzSoftware/complex pull request #948
Opened 2024-05-02 16:12 UTC by imikejackson

- https://github.com/BlueQuartzSoftware/simplnx/issues/944

- [ ] Unit test implemented for the added features
- [ ] Documentation updated to include the ordering of the data in the output array

2024-05-02 19:37 UTC, JDuffeyBQ requested changes

2024-05-02 19:37 UTC, JDuffeyBQ commented on src/simplnx/DataStructure/Geometry/RectGridGeom.cpp
> +  auto zBnds = getZBounds();
```suggestion
  const auto& xBnds = getXBoundsRef();
  const auto& yBnds = getYBoundsRef();
  const auto& zBnds = getZBoundsRef();
```

2024-05-02 19:37 UTC, JDuffeyBQ commented on src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CalculateFeatureSizesFilter.cpp
> +          index = (imageDims[1] * imageDims[0] * z) + (imageDims[0] * y) + x; // Index into featureIds array
Looks like this is only used inside the loop so the declaration can just become this line.

2024-05-02 19:37 UTC, JDuffeyBQ commented on src/simplnx/DataStructure/Geometry/RectGridGeom.cpp
> +  minCoords[2] = static_cast<float32>((*zBnds)[z]);
```suggestion
  minCoords[0] = static_cast<float32>(xBnds[x]);
  minCoords[1] = static_cast<float32>(yBnds[y]);
  minCoords[2] = static_cast<float32>(zBnds[z]);
```

2024-05-02 19:37 UTC, JDuffeyBQ commented on src/simplnx/DataStructure/Geometry/RectGridGeom.cpp
> +  maxCoords[2] = (*zBnds)[z + 1];
```suggestion
  maxCoords[0] = xBnds[x + 1];
  maxCoords[1] = yBnds[y + 1];
  maxCoords[2] = zBnds[z + 1];
```

2024-07-08 16:56 UTC, closed without merging

2024-07-08 16:56 UTC, imikejackson commented
Closing this for now as there isn't funding to work the issue.