FILTER: Read Peregrine HDF5 File (Python)
BlueQuartzSoftware/complex pull request #964
Opened 2024-05-17 14:10 UTC by joeykleingers

Adding a new Python filter called Read Peregrine HDF5 File that reads an HDF5 file that is in Peregrine's format.  The filter is capable of reading the following data:

Slice Datasets
+ Segmentation results
+ Camera data
+ Part Ids
+ Sample Ids

Registered Datasets
+ Anomaly detection
+ X-Ray CT

Scan Datasets
+ Time of travel

The filter can also read sub-volumes of the datasets.

2024-05-17 17:39 UTC, imikejackson approved these changes

2024-05-20 13:28 UTC, JDuffeyBQ requested changes

2024-05-20 13:28 UTC, JDuffeyBQ commented on src/simplnx/Utilities/Parsing/HDF5/Readers/DatasetReader.hpp
> +  Result<> readIntoSpan(nonstd::span<T> data, const std::optional<std::vector<hsize_t>>& start = std::nullopt, const std::optional<std::vector<hsize_t>>& count = std::nullopt) const;
The documentation should be updated for the new arguments. It's unclear what they're used for.

2024-05-20 17:53 UTC, JDuffeyBQ approved these changes

2024-05-20 18:04 UTC, merged